management:  
  # zipkin:
  #   tracing:
  #     endpoint: http://10.10.253.214:9411/api/v2/spans
  # tracing:    
  #   sampling:
  #     probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
spring:
  rabbitmq: 
        addresses: amqp://guest:guest@10.10.253.214:5672
    
eureka:
  instance:
    securePort: ${server.port}
#    nonSecurePortEnabled: false
#    securePortEnabled: true
    leaseRenewalIntervalInSeconds: 7
    leaseExpirationDurationInSeconds: 9
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
    register-with-eureka: false
    fetch-registry: false
    heartbeat-executor-thread-pool-size: 5
    eureka-service-url-poll-interval-seconds: 10